# Generated by Django 2.0.2 on 2018-06-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summar',
            new_name='summary',
        ),
    ]
